version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 3039:5432
    volumes:
      - ~/apps/postgres-spikestats:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=spikestats_db