services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "3039:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env.production
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: ${POSTGRES_DB:-spikestats_db}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20
    networks:
      - spikestats

  next:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    env_file:
      - .env.production
    networks:
      - spikestats

volumes:
  postgres-data:

networks:
  spikestats:
    driver: bridge
