export enum InvoiceFilters {
    STARTDATEASC = "STARTDATEASC",
    STARTDATEDESC = "STARTDATEDESC",
    ENDDATEASC = "ENDDATEASC",
    ENDDATEDESC = "ENDDATEDESC",
    AMOUNTASC = "AMOUNTASC",
    AMOUNTDESC = "AMOUNTDESC",
    NAMEASC = "NAMEASC",
    NAMEDESC = "NAMEDESC"
}