import type { Metadata } from "next";
import "./globals.css";

import { auth } from "@/lib/auth/auth";
import { ReactElement } from "react";
import { QueryClient } from "react-query";
import Providers from "./providers";
import { GeistSans } from "geist/font/sans";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function Layout({ children, params }: { children: ReactElement, params: Promise<{ locale: string }> }) {
	const { locale } = await params
	const session = await auth()

	return (
		<html lang="en">
			<body className={`${GeistSans.className} text-black antialiased min-h-screen min-w-screen bg-background dark:bg-foreground dark:text-white`}>
				<Providers locale={locale} session={session}>
					{children}
				</Providers>
			</body>
		</html>
	);
}
