import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { SessionProvider } from "next-auth/react"
import { NextAuthProvider } from "@/lib/providers/NextAuthProvider";
import { LocaleProvider } from "@/lib/providers/LocaleProvider";
import { auth } from "@/lib/auth/auth";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
	params
}: Readonly<{
	children: React.ReactNode;
	params:{
		locale: string;
	}
}>) {
	const session = await auth()
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen min-w-screen bg-background dark:bg-foreground dark:text-white`}>
				<NextAuthProvider session={session}>
					<LocaleProvider locale={params.locale}>
						{children}
					</LocaleProvider>
				</NextAuthProvider>
			</body>
		</html>
	);
}
