name: Build and Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variables
        id: vars
        run: |
          DATE=$(date +'%Y.%m.%d')
          VERSION="v${DATE}"

          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "TARGET=prod" >> $GITHUB_OUTPUT
            echo "SERVICE=next-prod" >> $GITHUB_OUTPUT
            echo "TAGS=-t antoineg3802/spikestats:${VERSION} -t antoineg3802/spikestats:latest" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF##*/}" == "develop" ]]; then
            echo "TARGET=dev" >> $GITHUB_OUTPUT
            echo "SERVICE=next-dev" >> $GITHUB_OUTPUT
            echo "TAGS=-t antoineg3802/spikestats:${VERSION}-dev -t antoineg3802/spikestats:latest-dev" >> $GITHUB_OUTPUT
          else
            echo "Invalid branch"
            exit 1
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --target ${{ steps.vars.outputs.TARGET }} \
            ${{ steps.vars.outputs.TAGS }} \
            --push .

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /chemin/vers/ton/projet
            docker-compose pull ${{ steps.vars.outputs.SERVICE }}
            docker-compose up -d --no-deps ${{ steps.vars.outputs.SERVICE }}
